spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/adotapet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
redis.host=${REDIS_HOST:localhost}
redis.port=${REDIS_PORT:6379}
redis.password=${REDIS_PASSWORD:}
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}
